#pragma once
#include <stdint.h>

// Части речи: варианты-ловушки в квизе берутся из той же группы,
// чтобы выбор был не очевиден по форме слова.
enum Pos : uint8_t { NOUN, VERB, ADJ, OTHER, NUM };

struct Word {
  const char* sv;
  const char* ru;
  Pos pos;
};

static const Word WORDS[] = {
  // --- существительные: люди и семья
  {"en man", "мужчина", NOUN},
  {"en kvinna", "женщина", NOUN},
  {"ett barn", "ребёнок", NOUN},
  {"en pojke", "мальчик", NOUN},
  {"en flicka", "девочка", NOUN},
  {"en mamma", "мама", NOUN},
  {"en pappa", "папа", NOUN},
  {"en bror", "брат", NOUN},
  {"en syster", "сестра", NOUN},
  {"en son", "сын", NOUN},
  {"en dotter", "дочь", NOUN},
  {"en vän", "друг", NOUN},
  {"en familj", "семья", NOUN},
  {"en granne", "сосед", NOUN},
  {"en läkare", "врач", NOUN},
  {"en lärare", "учитель", NOUN},
  {"en elev", "ученик", NOUN},
  {"en mormor", "бабушка (по маме)", NOUN},
  {"en farfar", "дедушка (по папе)", NOUN},
  // дом и быт
  {"ett hus", "дом", NOUN},
  {"en lägenhet", "квартира", NOUN},
  {"ett rum", "комната", NOUN},
  {"ett kök", "кухня", NOUN},
  {"ett badrum", "ванная", NOUN},
  {"en dörr", "дверь", NOUN},
  {"ett fönster", "окно", NOUN},
  {"ett bord", "стол", NOUN},
  {"en stol", "стул", NOUN},
  {"en säng", "кровать", NOUN},
  {"en soffa", "диван", NOUN},
  {"en lampa", "лампа", NOUN},
  {"en nyckel", "ключ", NOUN},
  {"en spegel", "зеркало", NOUN},
  {"ett golv", "пол", NOUN},
  {"ett tak", "крыша, потолок", NOUN},
  {"en trappa", "лестница", NOUN},
  {"en kudde", "подушка", NOUN},
  {"ett täcke", "одеяло", NOUN},
  // еда
  {"mat", "еда", NOUN},
  {"ett bröd", "хлеб", NOUN},
  {"smör", "масло", NOUN},
  {"en ost", "сыр", NOUN},
  {"mjölk", "молоко", NOUN},
  {"vatten", "вода", NOUN},
  {"kaffe", "кофе", NOUN},
  {"te", "чай", NOUN},
  {"ett ägg", "яйцо", NOUN},
  {"kött", "мясо", NOUN},
  {"en fisk", "рыба", NOUN},
  {"en kyckling", "курица", NOUN},
  {"ett äpple", "яблоко", NOUN},
  {"ett päron", "груша", NOUN},
  {"en banan", "банан", NOUN},
  {"en potatis", "картофель", NOUN},
  {"en morot", "морковь", NOUN},
  {"en lök", "лук", NOUN},
  {"socker", "сахар", NOUN},
  {"salt", "соль", NOUN},
  {"en tårta", "торт", NOUN},
  {"en bulle", "булочка", NOUN},
  {"glass", "мороженое", NOUN},
  {"en frukost", "завтрак", NOUN},
  {"en lunch", "обед", NOUN},
  {"en middag", "ужин", NOUN},
  {"en sked", "ложка", NOUN},
  {"en gaffel", "вилка", NOUN},
  {"en kniv", "нож", NOUN},
  {"en tallrik", "тарелка", NOUN},
  {"en kopp", "чашка", NOUN},
  {"ett glas", "стакан", NOUN},
  // город и транспорт
  {"en stad", "город", NOUN},
  {"en gata", "улица", NOUN},
  {"en väg", "дорога", NOUN},
  {"en bil", "машина", NOUN},
  {"en buss", "автобус", NOUN},
  {"ett tåg", "поезд", NOUN},
  {"en cykel", "велосипед", NOUN},
  {"ett flygplan", "самолёт", NOUN},
  {"en båt", "лодка", NOUN},
  {"en affär", "магазин", NOUN},
  {"en skola", "школа", NOUN},
  {"ett sjukhus", "больница", NOUN},
  {"en kyrka", "церковь", NOUN},
  {"en bro", "мост", NOUN},
  {"ett torg", "площадь", NOUN},
  {"en station", "вокзал, станция", NOUN},
  {"en biljett", "билет", NOUN},
  {"pengar", "деньги", NOUN},
  {"ett jobb", "работа", NOUN},
  {"ett kontor", "офис", NOUN},
  // природа
  {"en sol", "солнце", NOUN},
  {"en måne", "луна", NOUN},
  {"en stjärna", "звезда", NOUN},
  {"en himmel", "небо", NOUN},
  {"ett moln", "облако", NOUN},
  {"regn", "дождь", NOUN},
  {"snö", "снег", NOUN},
  {"is", "лёд", NOUN},
  {"en vind", "ветер", NOUN},
  {"ett väder", "погода", NOUN},
  {"ett träd", "дерево", NOUN},
  {"en blomma", "цветок", NOUN},
  {"en skog", "лес", NOUN},
  {"en sjö", "озеро", NOUN},
  {"ett hav", "море", NOUN},
  {"ett berg", "гора", NOUN},
  {"en ö", "остров", NOUN},
  {"en strand", "пляж, берег", NOUN},
  {"gräs", "трава", NOUN},
  {"en sten", "камень", NOUN},
  // животные
  {"en hund", "собака", NOUN},
  {"en katt", "кошка", NOUN},
  {"en häst", "лошадь", NOUN},
  {"en ko", "корова", NOUN},
  {"en gris", "свинья", NOUN},
  {"ett får", "овца", NOUN},
  {"en fågel", "птица", NOUN},
  {"en mus", "мышь", NOUN},
  {"en björn", "медведь", NOUN},
  {"en varg", "волк", NOUN},
  {"en räv", "лиса", NOUN},
  {"en älg", "лось", NOUN},
  {"en hare", "заяц", NOUN},
  {"en anka", "утка", NOUN},
  // тело
  {"ett huvud", "голова", NOUN},
  {"ett öga", "глаз", NOUN},
  {"ett öra", "ухо", NOUN},
  {"en näsa", "нос", NOUN},
  {"en mun", "рот", NOUN},
  {"en tand", "зуб", NOUN},
  {"en hand", "рука (кисть)", NOUN},
  {"en arm", "рука", NOUN},
  {"ett ben", "нога", NOUN},
  {"en fot", "ступня", NOUN},
  {"ett hjärta", "сердце", NOUN},
  {"ett hår", "волосы", NOUN},
  {"en mage", "живот", NOUN},
  // одежда и вещи
  {"en tröja", "свитер", NOUN},
  {"en jacka", "куртка", NOUN},
  {"ett par byxor", "брюки", NOUN},
  {"en sko", "ботинок", NOUN},
  {"en mössa", "шапка", NOUN},
  {"en klänning", "платье", NOUN},
  {"en väska", "сумка", NOUN},
  {"en bok", "книга", NOUN},
  {"en tidning", "газета", NOUN},
  {"ett brev", "письмо", NOUN},
  {"en telefon", "телефон", NOUN},
  {"en dator", "компьютер", NOUN},
  {"en klocka", "часы", NOUN},
  {"en penna", "ручка", NOUN},
  {"ett papper", "бумага", NOUN},
  {"en present", "подарок", NOUN},
  // время
  {"en dag", "день", NOUN},
  {"en natt", "ночь", NOUN},
  {"en morgon", "утро", NOUN},
  {"en kväll", "вечер", NOUN},
  {"en vecka", "неделя", NOUN},
  {"en månad", "месяц", NOUN},
  {"ett år", "год", NOUN},
  {"en timme", "час", NOUN},
  {"en minut", "минута", NOUN},
  {"en sommar", "лето", NOUN},
  {"en vinter", "зима", NOUN},
  {"en vår", "весна", NOUN},
  {"en höst", "осень", NOUN},
  {"en fråga", "вопрос", NOUN},
  {"ett svar", "ответ", NOUN},
  {"ett språk", "язык (речь)", NOUN},
  {"ett ord", "слово", NOUN},
  {"ett namn", "имя", NOUN},
  {"en resa", "поездка", NOUN},
  {"en semester", "отпуск", NOUN},

  // --- глаголы
  {"att vara", "быть", VERB},
  {"att ha", "иметь", VERB},
  {"att göra", "делать", VERB},
  {"att gå", "идти", VERB},
  {"att komma", "приходить", VERB},
  {"att se", "видеть", VERB},
  {"att höra", "слышать", VERB},
  {"att säga", "сказать", VERB},
  {"att prata", "разговаривать", VERB},
  {"att tala", "говорить", VERB},
  {"att fråga", "спрашивать", VERB},
  {"att svara", "отвечать", VERB},
  {"att äta", "есть (кушать)", VERB},
  {"att dricka", "пить", VERB},
  {"att sova", "спать", VERB},
  {"att vakna", "просыпаться", VERB},
  {"att läsa", "читать", VERB},
  {"att skriva", "писать", VERB},
  {"att lyssna", "слушать", VERB},
  {"att titta", "смотреть", VERB},
  {"att arbeta", "работать", VERB},
  {"att leka", "играть", VERB},
  {"att spela", "играть (на чём-то)", VERB},
  {"att köpa", "покупать", VERB},
  {"att sälja", "продавать", VERB},
  {"att betala", "платить", VERB},
  {"att ge", "давать", VERB},
  {"att ta", "брать", VERB},
  {"att öppna", "открывать", VERB},
  {"att stänga", "закрывать", VERB},
  {"att springa", "бегать", VERB},
  {"att simma", "плавать", VERB},
  {"att flyga", "летать", VERB},
  {"att köra", "водить, ехать", VERB},
  {"att åka", "ехать", VERB},
  {"att resa", "путешествовать", VERB},
  {"att bo", "жить (проживать)", VERB},
  {"att leva", "жить", VERB},
  {"att älska", "любить", VERB},
  {"att tycka om", "нравиться", VERB},
  {"att vilja", "хотеть", VERB},
  {"att kunna", "мочь, уметь", VERB},
  {"att behöva", "нуждаться", VERB},
  {"att veta", "знать (факт)", VERB},
  {"att känna", "знать, чувствовать", VERB},
  {"att tänka", "думать", VERB},
  {"att förstå", "понимать", VERB},
  {"att lära sig", "учиться", VERB},
  {"att glömma", "забывать", VERB},
  {"att komma ihåg", "помнить", VERB},
  {"att hjälpa", "помогать", VERB},
  {"att vänta", "ждать", VERB},
  {"att börja", "начинать", VERB},
  {"att sluta", "заканчивать", VERB},
  {"att laga mat", "готовить еду", VERB},
  {"att tvätta", "стирать, мыть", VERB},
  {"att städa", "убирать", VERB},
  {"att sitta", "сидеть", VERB},
  {"att stå", "стоять", VERB},
  {"att ligga", "лежать", VERB},
  {"att sjunga", "петь", VERB},
  {"att dansa", "танцевать", VERB},
  {"att skratta", "смеяться", VERB},
  {"att gråta", "плакать", VERB},
  {"att hitta", "находить", VERB},
  {"att leta", "искать", VERB},
  {"att ringa", "звонить", VERB},
  {"att skicka", "отправлять", VERB},
  {"att bära", "нести", VERB},
  {"att visa", "показывать", VERB},
  {"att stanna", "остановиться", VERB},
  {"att bli", "становиться", VERB},
  {"att heta", "называться", VERB},
  {"att fika", "пить кофе с булочкой", VERB},

  // --- прилагательные
  {"stor", "большой", ADJ},
  {"liten", "маленький", ADJ},
  {"lång", "длинный, высокий", ADJ},
  {"kort", "короткий", ADJ},
  {"ny", "новый", ADJ},
  {"gammal", "старый", ADJ},
  {"ung", "молодой", ADJ},
  {"bra", "хороший", ADJ},
  {"dålig", "плохой", ADJ},
  {"glad", "радостный", ADJ},
  {"ledsen", "грустный", ADJ},
  {"arg", "злой", ADJ},
  {"trött", "уставший", ADJ},
  {"hungrig", "голодный", ADJ},
  {"sjuk", "больной", ADJ},
  {"frisk", "здоровый", ADJ},
  {"varm", "тёплый", ADJ},
  {"het", "горячий", ADJ},
  {"kall", "холодный", ADJ},
  {"snabb", "быстрый", ADJ},
  {"långsam", "медленный", ADJ},
  {"vacker", "красивый", ADJ},
  {"ful", "некрасивый", ADJ},
  {"dyr", "дорогой", ADJ},
  {"billig", "дешёвый", ADJ},
  {"lätt", "лёгкий", ADJ},
  {"svår", "трудный", ADJ},
  {"tung", "тяжёлый", ADJ},
  {"stark", "сильный", ADJ},
  {"svag", "слабый", ADJ},
  {"ren", "чистый", ADJ},
  {"smutsig", "грязный", ADJ},
  {"full", "полный", ADJ},
  {"tom", "пустой", ADJ},
  {"rolig", "весёлый, смешной", ADJ},
  {"tråkig", "скучный", ADJ},
  {"snäll", "добрый", ADJ},
  {"rädd", "испуганный", ADJ},
  {"söt", "милый, сладкий", ADJ},
  {"god", "вкусный", ADJ},
  {"mörk", "тёмный", ADJ},
  {"ljus", "светлый", ADJ},
  {"röd", "красный", ADJ},
  {"blå", "синий", ADJ},
  {"grön", "зелёный", ADJ},
  {"gul", "жёлтый", ADJ},
  {"svart", "чёрный", ADJ},
  {"vit", "белый", ADJ},
  {"grå", "серый", ADJ},
  {"brun", "коричневый", ADJ},
  {"rosa", "розовый", ADJ},
  {"viktig", "важный", ADJ},
  {"rätt", "правильный", ADJ},
  {"fel", "неправильный", ADJ},
  {"öppen", "открытый", ADJ},
  {"stängd", "закрытый", ADJ},
  {"nära", "близкий", ADJ},
  {"lycklig", "счастливый", ADJ},

  // --- наречия, числа, фразы
  {"ja", "да", OTHER},
  {"nej", "нет", OTHER},
  {"tack", "спасибо", OTHER},
  {"hej", "привет", OTHER},
  {"hej då", "пока", OTHER},
  {"förlåt", "извините", OTHER},
  {"varsågod", "пожалуйста (на)", OTHER},
  {"snälla", "пожалуйста (прошу)", OTHER},
  {"god morgon", "доброе утро", OTHER},
  {"god natt", "спокойной ночи", OTHER},
  {"idag", "сегодня", OTHER},
  {"igår", "вчера", OTHER},
  {"imorgon", "завтра", OTHER},
  {"nu", "сейчас", OTHER},
  {"sedan", "потом", OTHER},
  {"alltid", "всегда", OTHER},
  {"aldrig", "никогда", OTHER},
  {"ofta", "часто", OTHER},
  {"ibland", "иногда", OTHER},
  {"här", "здесь", OTHER},
  {"där", "там", OTHER},
  {"mycket", "много, очень", OTHER},
  {"lite", "немного", OTHER},
  {"också", "тоже", OTHER},
  {"bara", "только", OTHER},
  {"kanske", "может быть", OTHER},
  {"varför", "почему", OTHER},
  {"var", "где", OTHER},
  {"vad", "что", OTHER},
  {"vem", "кто", OTHER},
  {"när", "когда", OTHER},
  {"hur", "как", OTHER},
  {"vilken", "который", OTHER},
  {"och", "и", OTHER},
  {"eller", "или", OTHER},
  {"men", "но", OTHER},
  {"med", "с", OTHER},
  {"utan", "без", OTHER},
  {"en / ett", "один", NUM},
  {"två", "два", NUM},
  {"tre", "три", NUM},
  {"fyra", "четыре", NUM},
  {"fem", "пять", NUM},
  {"sex", "шесть", NUM},
  {"sju", "семь", NUM},
  {"åtta", "восемь", NUM},
  {"nio", "девять", NUM},
  {"tio", "десять", NUM},
  {"hundra", "сто", NUM},
  {"tusen", "тысяча", NUM},
};

static const uint16_t WORD_COUNT = sizeof(WORDS) / sizeof(WORDS[0]);
